version: '3'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    networks:
      - backend

  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080  # Adminer typically uses port 8080
    networks:
      - backend
    depends_on:
      - mysql

  order_service:
    image: alaeldinmusa/order_service:latest  # Replace with your Docker Hub username
    container_name: order-service-container
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: order
      MYSQL_USER: root  # Replace with a dedicated user for your application
      MYSQL_PASSWORD:   # Replace with a strong password
    ports:
      - "8082:8082"
    networks:
      - backend
    depends_on:
      - mysql

networks:
  backend:
    driver: bridge
