version: '3'

services:
  mongodb:

    image: mongo
    container_name: mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  spring-app:
    image: product-service:latest
    container_name: spring-app-container
    ports:
      - "8081:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/product
      # Add other environment variables if needed

volumes:
  mongodb-data:
